// vault.go — general-purpose secure credential vault for the Atlas agent.
//
// Credentials, passwords, TOTP seeds, and other secrets discovered or
// generated by the agent are stored in a dedicated Keychain item that is
// entirely separate from the API-key bundle.
//
// Keychain item:
//
//	service: com.projectatlas.vault
//	account: credentials
//	value:   JSON-encoded vault struct
package creds

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"time"
)

// VaultEntry is one credential record stored in the agent vault.
type VaultEntry struct {
	ID          string `json:"id"`
	Service     string `json:"service"`               // hostname or service name, e.g. "gmail.com"
	Label       string `json:"label"`                // human name, e.g. "Gmail – Atlas Agent"
	Username    string `json:"username"`             // email, username, or account ID
	Password    string `json:"password"`             // password, token, or secret value
	TOTPSecret  string `json:"totpSecret,omitempty"` // base32 TOTP seed (RFC 6238) — optional
	Notes       string `json:"notes,omitempty"`      // free-form context
	SessionName string `json:"sessionName,omitempty"` // named session label for multi-account support
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

// vaultDoc is the top-level JSON document stored in the Keychain item.
type vaultDoc struct {
	Entries []VaultEntry `json:"entries"`
}

const (
	vaultKeychainService = "com.projectatlas.vault"
	vaultKeychainAccount = "credentials"
)

// vaultMu serialises all read-modify-write operations on the vault Keychain item.
var vaultMu sync.Mutex

// VaultRead returns all vault entries. Returns an empty slice (not an error)
// when the Keychain item does not yet exist.
func VaultRead() ([]VaultEntry, error) {
	doc, err := vaultReadDoc()
	if err != nil {
		return nil, err
	}
	return doc.Entries, nil
}

// VaultStore writes a new entry to the vault. If entry.ID is empty a random
// 16-hex-char ID is generated. CreatedAt and UpdatedAt are set to now.
// Returns the assigned entry ID.
func VaultStore(entry VaultEntry) (string, error) {
	vaultMu.Lock()
	defer vaultMu.Unlock()

	doc, err := vaultReadDoc()
	if err != nil {
		return "", fmt.Errorf("vault: read before store: %w", err)
	}

	now := time.Now().UTC().Format(time.RFC3339)
	if entry.ID == "" {
		entry.ID = vaultNewID()
	}
	entry.CreatedAt = now
	entry.UpdatedAt = now

	doc.Entries = append(doc.Entries, entry)
	if err := vaultWriteDoc(doc); err != nil {
		return "", err
	}
	return entry.ID, nil
}

// VaultUpdate patches an existing entry identified by id. Only non-empty
// string fields in fields are applied; empty strings leave the existing
// value unchanged.
func VaultUpdate(id string, fields VaultEntry) error {
	vaultMu.Lock()
	defer vaultMu.Unlock()

	doc, err := vaultReadDoc()
	if err != nil {
		return fmt.Errorf("vault: read before update: %w", err)
	}

	now := time.Now().UTC().Format(time.RFC3339)
	found := false
	for i := range doc.Entries {
		if doc.Entries[i].ID != id {
			continue
		}
		e := &doc.Entries[i]
		if fields.Service != "" {
			e.Service = fields.Service
		}
		if fields.Label != "" {
			e.Label = fields.Label
		}
		if fields.Username != "" {
			e.Username = fields.Username
		}
		if fields.Password != "" {
			e.Password = fields.Password
		}
		if fields.TOTPSecret != "" {
			e.TOTPSecret = fields.TOTPSecret
		}
		if fields.Notes != "" {
			e.Notes = fields.Notes
		}
		e.UpdatedAt = now
		found = true
		break
	}
	if !found {
		return fmt.Errorf("vault: entry %q not found", id)
	}
	return vaultWriteDoc(doc)
}

// VaultDelete removes the entry with the given id.
func VaultDelete(id string) error {
	vaultMu.Lock()
	defer vaultMu.Unlock()

	doc, err := vaultReadDoc()
	if err != nil {
		return fmt.Errorf("vault: read before delete: %w", err)
	}

	before := len(doc.Entries)
	kept := doc.Entries[:0]
	for _, e := range doc.Entries {
		if e.ID != id {
			kept = append(kept, e)
		}
	}
	if len(kept) == before {
		return fmt.Errorf("vault: entry %q not found", id)
	}
	doc.Entries = kept
	return vaultWriteDoc(doc)
}

// ── internal helpers ──────────────────────────────────────────────────────────

// vaultReadDoc reads the vault Keychain item and unmarshals it.
// Returns an empty doc (not an error) when the item does not yet exist.
// Must be called with vaultMu held for read-modify-write patterns; safe to
// call without the lock for pure reads (VaultRead).
func vaultReadDoc() (vaultDoc, error) {
	out, err := execSecurity("find-generic-password",
		"-s", vaultKeychainService,
		"-a", vaultKeychainAccount,
		"-w",
	)
	if err != nil {
		// Item not present → return empty vault, not an error.
		return vaultDoc{Entries: []VaultEntry{}}, nil
	}

	var doc vaultDoc
	if err := json.Unmarshal([]byte(strings.TrimSpace(out)), &doc); err != nil {
		return vaultDoc{}, fmt.Errorf("vault: unmarshal: %w", err)
	}
	if doc.Entries == nil {
		doc.Entries = []VaultEntry{}
	}
	return doc, nil
}

// vaultWriteDoc marshals and persists the vault to the Keychain.
// Callers MUST hold vaultMu.
func vaultWriteDoc(doc vaultDoc) error {
	data, err := json.Marshal(doc)
	if err != nil {
		return fmt.Errorf("vault: marshal: %w", err)
	}
	_, err = execSecurity(
		"add-generic-password",
		"-U",
		"-s", vaultKeychainService,
		"-a", vaultKeychainAccount,
		"-w", string(data),
	)
	if err != nil {
		return fmt.Errorf("vault: write keychain: %w", err)
	}
	return nil
}

// vaultNewID generates a random 16-hex-character string for use as an entry ID.
func vaultNewID() string {
	b := make([]byte, 8)
	_, _ = rand.Read(b) // crypto/rand never errors on macOS
	return fmt.Sprintf("%x", b)
}
